# -*- coding: utf-8 -*-
"""Customer Churn analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHK3QDObbPIuWzb0hLXsD0S-9RV2-jxo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn-selected-columns.csv")
print (df)

from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

#view data
df.head()

#check shape
df.shape

#understand dataset
df.info()

df.describe()

#check missing values
df.isnull().sum()

#CLEAN TOTAL CHARGES
#1. Convert to numeric
df['Total_charges']=pd.to_numeric(df['TotalCharges'],
    errors='coerce')

#check missing values
df['TotalCharges'].isnull().sum()

# check churn distribution
sns.countplot(x='Churn', data=df)

plt.title("Customer Churn Distribution")
plt.show()

#Gender vs churn

sns.countplot(
    x='gender',
    hue='Churn',
    data=df
)

plt.show()

#Contract vs churn
sns.countplot(
    x='Contract',
    hue='Churn',
    data=df
)

plt.xticks(rotation=20)
plt.show()

#internet vs churn
sns.countplot(
    x='InternetService',
    hue='Churn',
    data=df
)

plt.show()

#monthly charges analysis
sns.boxplot(
    x='Churn',
    y='MonthlyCharges',
    data=df
)

plt.show()

#tenue analysis
plt.figure(figsize=(8,5))

sns.histplot(
    data=df,
    x='tenure',
    hue='Churn',
    bins=20
)

plt.show()

#senior citizen analysis
sns.countplot(
    x='SeniorCitizen',
    hue='Churn',
    data=df
)

plt.show()

#correlatio heatmap

#1. Convert Churn to numbers
df['Churn_Num'] = df['Churn'].map({
    'No':0,
    'Yes':1
})

#heatmap
corr = df.select_dtypes(include='number')

sns.heatmap(
    corr.corr(),
    annot=True
)

plt.show()

#Save Clean Dataset

df.to_csv(
    "cleaned_customer_churn.csv",
    index=False
)